server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
management:
  server:
    port: 9000
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'

springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  use-management-port: true
  group-configs:
  - group: application
    paths-to-match: /api/application/**
  - group: infrastructure
    paths-to-match: /api/infrastructure/**
# server.port: 8080
# management.server.port: 9001
# management.server.address: 127.0.0.1
# management.endpoints.web.exposure.include=*

# # swagger-ui custom path
# springdoc.swagger-ui.path=/swagger-ui.html
# springdoc.api-docs.path=/api-docs

# # Disabling the /v3/api-docs enpoint
# springdoc.api-docs.enabled=true
# # Disabling the swagger-ui
# springdoc.swagger-ui.enabled=true

# # Packages to include
# springdoc.packagesToScan=com.github.rlopezv.eeas.api
# # Paths to include
# #springdoc.pathsToMatch=/v1, /api/balance/**

# #springdoc.use-management-port=true
# # This property enables the openapi and swaggerui endpoints to be exposed beneath the actuator base path.
# #management.endpoints.web.exposure.include=openapi, swaggerui